// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZDBwu5BcGhFJ6CdosiQNEw9ykbds12U',
    appId: '1:697547285921:web:60e9b72480d163ffdd97e0',
    messagingSenderId: '697547285921',
    projectId: 'repaint-asgs',
    authDomain: 'repaint-asgs.firebaseapp.com',
    storageBucket: 'repaint-asgs.appspot.com',
    measurementId: 'G-LRP01F8Q5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7iaoDW7fyAUwvir9CciZEGuT0_wJGD_Y',
    appId: '1:697547285921:android:9c7445c848991bfddd97e0',
    messagingSenderId: '697547285921',
    projectId: 'repaint-asgs',
    storageBucket: 'repaint-asgs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYuUUWzADjgIDkb4Sz8CtaxQptDm77_y0',
    appId: '1:697547285921:ios:b255e2b46241066add97e0',
    messagingSenderId: '697547285921',
    projectId: 'repaint-asgs',
    storageBucket: 'repaint-asgs.appspot.com',
    iosBundleId: 'dev.asgs.repaint.repaintMobile',
  );
}
