#!/usr/bin/env bash
set -ex
(
  echo "API_BASE_URL=$API_BASE_URL"
  echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID"
  echo "AUTH0_DOMAIN=$AUTH0_DOMAIN"
  echo "AUTH0_SCHEME=$AUTH0_SCHEME"
  echo "SENTRY_DSN=$SENTRY_DSN"
  echo "SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT"
) > .env